<a href="https://colab.research.google.com/github/Naveenkumarnaveeen/Machine-Learning-with-Python/blob/main/class_9_%26_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Functions , Numpy 

In [2]:
# print(), input(), len(), min(), max(), sum() - in built functions 
# a block of code which is defined by the user which can be used repeatedly - user defined functions 

In [3]:
# SYNTAX OF A USER DEFINED FUNCTION 
# def functionname(parameters):      function definition
#   # statements/expressions 
#   # statements/expressions

# functionname()                   #function call

In [4]:
def my_func():
  print("Hello World")
  print("HELLO WORLD!")

In [5]:
my_func()
my_func()
my_func()

Hello World
HELLO WORLD!
Hello World
HELLO WORLD!
Hello World
HELLO WORLD!


In [6]:
def num():
  number = int(input("Enter the number :"))
  print("The entered number is :",number)

num()  #function call

Enter the number :6
The entered number is : 6


In [7]:
def num1(x):
  print(x*x)

num1(7)

49


In [8]:
def add(x,y):
  sum = x + y
  return sum

add(3,5)

8

In [9]:
def calc1(x,y):
  add = x+y
  sub = x-y
  mul = x*y
  div = x/y
  return add,sub,mul,div


calc1(2,3)

(5, -1, 6, 0.6666666666666666)

In [10]:
# FILE HANDLING 

#create a file 
f = open('abc.txt',"w")    #w - write mode 
print(f)

<_io.TextIOWrapper name='abc.txt' mode='w' encoding='UTF-8'>


In [11]:
f = open('abc.txt',"r")   # read mode 
f

<_io.TextIOWrapper name='abc.txt' mode='r' encoding='UTF-8'>

In [12]:
f = open('abc.txt',"a")   #append mode 
f.write("Welcome!")

8

In [13]:
f = open('abc.txt',"r") 
print(f.read())

In [14]:
# used to create a separate from
%%writefile demo.txt
# %%writefile filename.extension
# magic command is used here to create a file 
google colaboratory 
is an online editor 

Writing demo.txt


In [15]:
#NumPy - Numerical python 
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [16]:
import numpy as np  

In [17]:
a = [1,2,3,4,5]
type(a)

list

In [18]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [19]:
a.ndim

1

In [20]:
a = np.array(50)
a

array(50)

In [21]:
a.ndim

0

In [22]:
a = np.array([[1,2,3,4,5]])
a

array([[1, 2, 3, 4, 5]])

In [23]:
a.ndim # number of dimensions of the array

2

In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
a.shape  # shape of the array(rows,columns)

(2, 5)

In [26]:
a.size   #total number of elements in the array

10

In [27]:
a.ndim  #number of dimensions

2

In [28]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [29]:
a.ndim

3

In [30]:
# higher dimensions arrays  (max - 32 dimensions)
a = np.array([1,2,3,4,5],ndmin = 7)
a

array([[[[[[[1, 2, 3, 4, 5]]]]]]])

In [31]:
a.ndim

7

In [32]:
a = np.array([4,6,7,8,4,3,2])
a

array([4, 6, 7, 8, 4, 3, 2])

In [45]:
b = np.array([5,7,8,4,3,5,9])
b

array([5, 7, 8, 4, 3, 5, 9])

In [34]:
a.shape

(7,)

In [35]:
a.dtype    # prints the datatype of the elements inside the numpy array 

dtype('int64')

In [36]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [37]:
a[3]

8

In [38]:
a[-5]

7

In [39]:
a[0:4]

array([4, 6, 7, 8])

In [40]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [41]:
b

array([5, 7, 8, 4, 3, 5, 9])

In [46]:
a+b 

array([ 9, 13, 15, 12,  7,  8, 11])

In [47]:
a-b

array([-1, -1, -1,  4,  1, -2, -7])

In [48]:
a*b

array([20, 42, 56, 32, 12, 15, 18])

In [49]:
a/b

array([0.8       , 0.85714286, 0.875     , 2.        , 1.33333333,
       0.6       , 0.22222222])

In [50]:
a%b

array([4, 6, 7, 0, 1, 3, 2])

In [51]:
a//b

array([0, 0, 0, 2, 1, 0, 0])

In [52]:
a**2  # broadcasting of a numpy array 

array([16, 36, 49, 64, 16,  9,  4])

In [53]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [54]:
a/2.56  # broadcasting of a numpy array 

array([1.5625  , 2.34375 , 2.734375, 3.125   , 1.5625  , 1.171875,
       0.78125 ])

In [55]:
a*7.89  # broadcasting of a numpy array 

array([31.56, 47.34, 55.23, 63.12, 31.56, 23.67, 15.78])

In [56]:
a+5   # broadcasting of a numpy array 

array([ 9, 11, 12, 13,  9,  8,  7])

In [57]:
a[0]+b[4] # mathematical operations according to index also works

7

In [58]:
np.sort(a)

array([2, 3, 4, 4, 6, 7, 8])

In [59]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [60]:
np.sort(b) #acsending order sort 

array([3, 4, 5, 5, 7, 8, 9])

In [61]:
np.sort(b)[::-1] #descending order sort 

array([9, 8, 7, 5, 5, 4, 3])

In [62]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [63]:
np.min(a)

2

In [64]:
np.max(a)

8

In [65]:
np.sum(a)

34

In [66]:
np.mean(a)

4.857142857142857

In [67]:
np.abs(a)  #absolute values (removes the +ve or -ve sign from the number)

array([4, 6, 7, 8, 4, 3, 2])

In [68]:
np.exp(a)  #exponential values 

array([  54.59815003,  403.42879349, 1096.63315843, 2980.95798704,
         54.59815003,   20.08553692,    7.3890561 ])

In [69]:
np.sqrt(a) # square root of all numbers in the array

array([2.        , 2.44948974, 2.64575131, 2.82842712, 2.        ,
       1.73205081, 1.41421356])

In [71]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [70]:
np.power(a,2)

array([16, 36, 49, 64, 16,  9,  4])

In [72]:
np.power(a,3)

array([ 64, 216, 343, 512,  64,  27,   8])

In [73]:
np.power(a,4)

array([ 256, 1296, 2401, 4096,  256,   81,   16])

In [74]:
np.sin(a)

array([-0.7568025 , -0.2794155 ,  0.6569866 ,  0.98935825, -0.7568025 ,
        0.14112001,  0.90929743])

In [75]:
np.cos(a)

array([-0.65364362,  0.96017029,  0.75390225, -0.14550003, -0.65364362,
       -0.9899925 , -0.41614684])

In [76]:
np.tan(a)

array([ 1.15782128, -0.29100619,  0.87144798, -6.79971146,  1.15782128,
       -0.14254654, -2.18503986])

In [77]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [78]:
np.argmin(a)  # index of the smallest element

6

In [79]:
np.argmax(a)  #index of the maximum element

3

In [80]:
# np.sort()
# np.abs()
# np.exp()
# np.argmin()
# np.argmax()
# np.sin()
# np.cos()
# np.tan()
# np.power()
# np.sqrt()
# np.min()
# np.max()
# np.sum() 
# broadcasting 

In [81]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [83]:
np.ones([10,10],dtype ='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [84]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
np.zeros([10,10],dtype = 'int64')  #int8 - 8bits, int16 - 16bits, int32 - 32 bits, int64 - 64 bits 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [87]:
np.array(['aa','bb','cc','dd'])       # U2 - unicode character string of 2 characters

array(['aa', 'bb', 'cc', 'dd'], dtype='<U2')

In [88]:
np.array(['aaa','bbb','ccc','ddd'])   # U3 - unicode character string of 3 characters

array(['aaa', 'bbb', 'ccc', 'ddd'], dtype='<U3')

In [89]:
np.array(['aaaaa','bbb','cccc','ddd']) 

array(['aaaaa', 'bbb', 'cccc', 'ddd'], dtype='<U5')

In [90]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [91]:
np.arange(0,50,2)    # numpy array from 0 to 50 in steps of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [92]:
np.arange(0,10,5)

array([0, 5])

In [93]:
# linspace - Return evenly spaced numbers over a specified interval.
np.linspace(0,50,2)  # divides the array into two equal values 

array([ 0., 50.])

In [94]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [95]:
a

array([4, 6, 7, 8, 4, 3, 2])

In [96]:
b

array([5, 7, 8, 4, 3, 5, 9])

In [97]:
#concatenate an array
ab = np.concatenate((a,b))
ab

array([4, 6, 7, 8, 4, 3, 2, 5, 7, 8, 4, 3, 5, 9])

In [98]:
np.unique(ab)  #prints the unique elements in the numpy array 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.unique(ab,return_counts = True)  

#prints the unique elements in the numpy array & 
# prints how times each element has been repeated in the array

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 2, 1, 2, 2, 1]))

In [100]:
# RANDOM NUMBER GENERATION 
x = np.random.rand(5,5)     # 5x5 matrix of random numbers 
x

array([[0.942217  , 0.84341939, 0.03055452, 0.83408666, 0.13222894],
       [0.48833724, 0.83777447, 0.13845231, 0.15999278, 0.04435759],
       [0.46050984, 0.54844948, 0.14381683, 0.90345584, 0.32593243],
       [0.5176753 , 0.52080178, 0.06346577, 0.86617354, 0.23708383],
       [0.31537626, 0.62422273, 0.01253611, 0.89325062, 0.80758763]])

In [101]:
np.random.randint(0,100,1)  #prints 1 random value in between 0 and 100

array([76])

In [102]:
np.random.randint(0,100,10)  #prints 10 random values in between 0 and 100

array([95, 35, 26, 35, 77, 64, 94, 58, 59, 92])

In [103]:
#OTP generation using numpy random integers 
print(np.random.randint(0,10,6))

[3 3 9 5 5 1]


In [104]:
#creates a 5x5 random integers matrix of only odd numbers
np.random.choice([1,3,5,7,9],size = [5,5])  

array([[3, 7, 7, 7, 5],
       [1, 5, 5, 1, 1],
       [3, 5, 7, 3, 7],
       [7, 3, 1, 1, 9],
       [9, 7, 5, 3, 7]])

In [105]:
#creates a 5x5 random integers matrix of only even numbers
np.random.choice([0,2,4,6,8],size = [5,5])  

array([[6, 2, 8, 4, 2],
       [2, 6, 6, 0, 8],
       [6, 6, 8, 2, 4],
       [2, 6, 2, 6, 0],
       [0, 4, 4, 0, 6]])

In [106]:
# random.seed - The seed() method is used to initialize the random number generator.   (# Seed must be between 0 and 2**32 - 1)
np.random.seed(54364) # seed number can be anything (ex- 12452142 or 124 or 0 or 4634523) 
np.random.randint(0,100,30)

array([ 4, 20, 33, 53, 19, 85, 55,  5, 54, 71, 77, 77, 93, 91,  8,  4, 86,
       96, 20,  6, 89,  0, 17, 14, 94, 34, 67, 92, 76, 97])